framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%locale%'
    translator:
        fallbacks: ['%locale%']
    csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: snc_redis.session.handler
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
        app: cache.adapter.redis
        default_redis_provider: snc_redis.default
    # Put the unique name of your app here: the prefix seed
    # is used to compute stable namespaces for cache keys.
    #prefix_seed: your_vendor_name/app_name

    # The app cache caches to the filesystem by default.
    # Other options include:

    # Redis
    #app: cache.adapter.redis
    #default_redis_provider: redis://localhost

    # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
    #app: cache.adapter.apcu

knp_paginator:
    page_range: 5
    default_options:
        page_name: p
        distinct: true
    template:
        pagination: 'pagination.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
